### ISSUE TITLE
Make manager/depositor/viewer permissions more clear

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#120]
It's very unclear that a manager, depositor, viewer can only see those works that are deposited after they gain permissions to the admin set. I think we need to add language in this screen to make it clear. This has been a surprise to many testers, so I thought I'd write this up as a minimal thing to do before a larger effort happens.

**Suggest something like this:** 
Individuals granted permission below will only have access to items (works?) deposited after their permission is granted.

**Comment by vantuyls** [comment]
this seems like a fine approach to me.

**Comment by elrayle** [comment]
I support adding the suggested text.  I spend a lot of my time explaining to people that anything created before the change is NOT updated.

I also strongly recommend setting participants using Groups instead of Users.  If you have a manager group and you remove/add users to the group, then those changes will impact existing works.

**Comment by julesies** [comment]
I would add the text about groups, but since there is no way to use a group I thought that would be frustrating. We will make this very clear in the repo managers documentation.

**Comment by vantuyls** [comment]
fix for 2.0 with suggested language

**Comment by elrayle** [comment]
@jrr I believe this is fixed and can be closed.  Can you confirm?

**Comment by julesies** [comment]
yes confirmed on nurax.
