### ISSUE TITLE
Viewer Access to Admin Set

### ISSUE THREAD

**Issue by chrisdaaz** [samvera-labs/nurax-pre2023#121]
### Descriptive summary

Viewers currently have no access to admin sets for which they have been designated a Viewer Role. Here's what seems to be missing:

- Notification that they have been added as a Viewer to an Admin Set
- Ability to see the Admin Set in the Administrative Sets (`/admin/admin_sets`) panel
- Ability to see pending Works in the Admin Set from the Review Submissions (`/admin/workflows`) panel

From what I can tell, when a user has been given the Viewer role in an Admin Set, the only thing they are able to do is view a work that is in that Admin Set, pending approval, if they have been given a direct URL. There is no way to navigate to that work, or know that it's there. 

### Expected behavior

Viewers should be notified when they've been given View access to an Admin Set and should be able to navigate to that Admin Set and take actions on Works in that Admin Set.

### Actual behavior

Here is an Admin Set with a Work that is pending approval:
![image](https://user-images.githubusercontent.com/24395592/32026338-8c028888-b9a9-11e7-9ddb-3f183dd47acc.png)

Here are the participants of the Admin Set:
![image](https://user-images.githubusercontent.com/24395592/32026355-acdecb34-b9a9-11e7-8102-e307760063d5.png)

Here is what the Viewer can see from their Admin Sets panel (note: they can't see the Admin Set they're supposed to View):
![image](https://user-images.githubusercontent.com/24395592/32026382-cbd7c6da-b9a9-11e7-8cae-01ed796d4360.png)

Here is what they see when the try to view their submissions (note: these are works from admin sets for which the user is a Manager; none of these are from the admin set for which the user is a Viewer): 
![image](https://user-images.githubusercontent.com/24395592/32026410-eb65ff58-b9a9-11e7-94bd-0d2fba988ed8.png)

No notifications:
![image](https://user-images.githubusercontent.com/24395592/32026469-2633b512-b9aa-11e7-931d-82449f8e07a7.png)

The purpose of the Viewer role is not clear to me.

### Questions

- What am I missing?
- Should we add capabilities to the Viewer role?
- Should we remove the Viewer role?

**Comment by chrisdaaz** [comment]
i tested this again today. same problem. i added another work to the admin set (as a registered user), then checked the Viewer account to see if the work appears in the Review Submissions panel and if the Admin Set appears in the Administrative Sets panel.

**Comment by chrisdaaz** [comment]
Might be noted already here: https://github.com/samvera/hyrax/issues/565

**Comment by elrayle** [comment]
I saw this as well in collections-extensions and was unclear if the inability to view the admin-set was intentional.  What does happen with the viewer role is that when a work is created, the admin-set viewers are given `read-access` to the new work.

@jcoyne @mjgiarlo What is the intended behavior for Viewers of admin-sets?  Can you check which of these you expect to apply.
- [ ] Viewer is assigned `read access` to the admin set
- [ ] Viewer is assigned `read access` to new works
- [ ] Viewer is assigned `reviewer role` to new works that have mediated deposit workflow

FYI... for collections in collection extensions
- [x] Viewer is assigned `read access` to the collection (meaning they see the collection in Dashboard -> Collections -> Managed Collections and can view the collection's admin show page)
- [x] Viewer is assigned `read access` to new works (when created directly in the collection)
- [ ] Viewer is assigned `reviewer role` to new works that have mediated deposit workflow (Collections do not impact workflows, so this is NOT assigned based on a collection)

**Comment by vantuyls** [comment]
2.x

**Comment by laritakr** [comment]
My memory of the purpose of the viewer role (based on discussion last fall) was that the Viewer would receive read access to any works created in the admin set after the point in time where they were added as viewer. There was no implied access to the admin set itself at that time, and no retroactive access given to works created prior to the point that the Viewer role was assigned.

This would imply that they need some other way to access the works they are given access to, if the admin set is not the access method.

**Comment by elrayle** [comment]
FYI...  I am working on the documentation for the impact of adding/removing participants for collection types, collections, and admin sets.  This should include information on what happens with the workflows, but I don't have that knowledge yet.  I'm working with @laritakr to understand the impact.  If others have feedback that would also be good to hear.
 http://elr37-dev.library.cornell.edu/samvera_docs/collection_extensions_faq_participants.html

**Comment by elrayle** [comment]
@vantuyls @julesies Is there a Hyrax issue for this?

**Comment by vantuyls** [comment]
https://github.com/samvera/hyrax/issues/2004

**Comment by chrisdaaz** [comment]
confirmed that viewers have read access to works published in admin sets and can view the admin set from the dashboard under managed collections. viewers are **not** granted the role of reviewer for admin sets with one-step mediated deposit enabled.
