### ISSUE TITLE
SWW error when adding Embargoed work to collection

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#176]
If I add an existing embargoed work to an existing collection I get the SWW error. 

from Lynette on Slack:
I got it with Dashboard -> Works -> check a box beside a work -> Add to collection -> select a collection -> Save updates -----  SWW

**Comment by elrayle** [comment]
This is most likely caused by turbolinks.  Turning turbolinks off on the link that launches the modal will likely fix this issue.

A quick test when the problem occurs...
* cancel the modal
* refresh the page
* relaunch the modal

If this fixes the problem, then it is definitely a turbolinks issue.  

See https://github.com/samvera/hyrax/issues/1191.

**Comment by julesies** [comment]
@elrayle is this a dupe? not sure why i reported it twice  https://github.com/curationexperts/nurax/issues/138

**Comment by elrayle** [comment]
Dup of Issue #138
