### ISSUE TITLE
Import from box strips file extension

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#233]
Import from box works successfully and the file imports to hyrax, however when a user downloads the file they see a generic file on their computer: download 

Example: https://nurax.curationexperts.com/concern/generic_works/7m01bk73c?locale=en

**Comment by julesies** [comment]
related: https://github.com/samvera/hyrax/issues/1684

**Comment by cjcolvar** [comment]
Retested after nurax was updated to 2.1.0.rc3.  While the uploads now succeed, this issue is still present.  I believe this might be the case for any browse-everything content and not just Box.  I believe the culprit line is https://github.com/samvera/hyrax/blob/master/app/jobs/import_url_job.rb#L54.  Instead of just assuming the url's path is the correct filename we may have to retrieve it some other way.  The other possible candidate is in the downloads concern: https://github.com/samvera/hyrax/blob/master/app/controllers/concerns/hyrax/local_file_downloads_controller_behavior.rb#L46-L49

**Comment by chrisdaaz** [comment]
moved to hyrax
